
const USER_ACTIONS = {
    ADD: 'ADD',
    DELETE : "DELETE",
    LOGIN_WORKSHOP: 'LOGIN_WORKSHOP',

    COUNT_DOWN: 'COUNT_DOWN',
    GET_USERS_REQUEST_TAKE: 'GET_USERS_REQUEST_TAKE',
    GET_USERS_REQUEST_TAKE_FORK: 'GET_USERS_REQUEST_TAKE_FORK',
    GET_USERS_REQUEST_TAKE_UNBLOCK: 'GET_USERS_REQUEST_TAKE_UNBLOCK',


    GET_USERS_REQUEST_LATEST: 'GET_USERS_REQUEST_LATEST',
    GET_USERS_REQUEST_EVERY: 'GET_USERS_REQUEST_EVERY',
    GET_USERS_REQUEST_LEADING:'GET_USERS_REQUEST_LEADING',
    GET_USERS_REQUEST_MAYBE:'GET_USERS_REQUEST_MAYBE',
    CHANNEL_REQUEST:'CHANNEL_REQUEST',
    CHANNEL_REQUEST_FORK:'CHANNEL_REQUEST_FORK',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS'
}

export default USER_ACTIONS;