
const USER_ACTIONS = {
    ADD: 'ADD',
    DELETE : "DELETE",

    GET_USERS_REQUEST_TAKE: 'GET_USERS_REQUEST_TAKE',
    GET_USERS_REQUEST_TAKE_UNBLOCK: 'GET_USERS_REQUEST_TAKE_UNBLOCK',


    GET_USERS_REQUEST_LATEST: 'GET_USERS_REQUEST_LATEST',
    GET_USERS_REQUEST_EVERY: 'GET_USERS_REQUEST_EVERY',
    GET_USERS_REQUEST_LEADING:'GET_USERS_REQUEST_LEADING',
    GET_USERS_REQUEST_MAYBE:'GET_USERS_REQUEST_MAYBE',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS'
}

export default USER_ACTIONS;